[project]
name = "weather-server-jayden"
version = "0.1.0"
description = "MCP 날씨 서버 Example!"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.22.0",
]

[project.scripts]
weather-server = "weather:main"